### ISSUE TITLE
error installing this on macos arm64

### ISSUE THREAD

**Issue by grisaitis** [conda-forge/r-pak-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

(repost of https://github.com/r-lib/pak/issues/480)

for some reason, installation is failing on my macos arm64 machine. verbose mode isn't telling me anything (that i can interpret as useful, anyway). 

any tips? is this user error? or something wrong with the package on conda-forge?

```shell
❯ conda create -v -n myenv -c conda-forge "r-pak"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                             
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/install.py", line 291, in install
    raise e
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/install.py", line 260, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 319, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 853, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/resolve.py", line 1323, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError
```

### Installed packages

```shell
new env
```

### Environment info

```shell
active environment : base
    active env location : /Users/william/.pyenv/versions/miniforge3
            shell level : 0
       user config file : /Users/william/.condarc
 populated config files : /Users/william/.pyenv/versions/miniforge3/.condarc
                          /Users/william/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/william/.pyenv/versions/miniforge3  (writable)
      conda av data dir : /Users/william/.pyenv/versions/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/william/.pyenv/versions/miniforge3/pkgs
                          /Users/william/.conda/pkgs
       envs directories : /Users/william/.pyenv/versions/miniforge3/envs
                          /Users/william/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.10 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mfansler** [comment]
Since this package is `noarch`, it technically is already compatible with **osx-arm64**, however, one or more of its dependencies must not be. First up, seems like we need to build `r-lpsolve`:

```bash
% CONDA_SUBDIR=osx-arm64 mamba create -n foo r-pak r-base=4.2

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['r-pak', 'r-base=4.2']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
pkgs/main/osx-arm64                                         Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/osx-arm64                                            Using cache
pkgs/r/noarch                                               Using cache
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides r-lpsolve needed by r-pak-0.1.2-r35h6115d3f_0

The environment can't be solved, aborting the operation
```

I will start the process of migrating it.

**Comment by mfansler** [comment]
It appears `r-lpsolve` was the only missing dependency. The `CONDA_SUBDIR=osx-arm64 mamba create -n foo r-pak` command now works for me. Please reopen if there are any further issues.
